config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  get 'events/filter/past' => 'events#index', filter: 'past'
  resources :events do
    get :join, to:'events#join', as: 'join'
  end
  resource :session
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :location, :description, presence: true

  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :user_events
  has_many :attendees, through: :user_events, class_name: 'User', dependent: :destroy

  scope :past, -> { where('starts_at < ?', Time.now).order('starts_at') }
  scope :upcoming, -> { where('starts_at >= ?', Time.now).order('starts_at') }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: 'Event', foreign_key: 'user_id', dependent: :destroy
  has_many :user_events
  has_many :attended_events, through: :user_events, class_name: 'Event', dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/user_event.rb
class UserEvent < ApplicationRecord
  belongs_to :attendee, class_name: 'User', foreign_key: 'user_id'
  belongs_to :attended_event, class_name: 'Event', foreign_key: 'event_id'

  def self.join_event(user_id, event_id)
    new(user_id: user_id, event_id: event_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def sign_in
    redirect_to new_session_path, notice: 'Please sign in first' unless current_user
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :sign_in, only: %i[join show]

  def index
    @events = case params[:filter]
              when 'past'
                Event.past
              else
                Event.upcoming
              end
  end

  def show
    @event = Event.find(params[:id])
    @users = User.all

    @current_attendee = current_user.user_events.find_by(event_id: @event.id) if current_user
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'Event created'
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    @event.update(event_params)
    redirect_to @event
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  def join
    # flash[:notice] = params
    # redirect_to event_path(params[:event_id])

    @user_event = UserEvent.join_event(params[:user_id], params[:event_id])
    if @user_event.save # rubocop:disable Style/GuardClause
      flash[:notice] = 'Successfully Joined event'
      redirect_to event_path(params[:event_id])
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :location, :starts_at)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_name(params[:name])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: "You are signed in #{user.name}"
    else
      flash.now[:notice] = 'Your are not a user'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, notice: 'You signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_in, except: %i[new create]
  before_action :set_params, only: %i[edit show update destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'New User created and logged in!'
    else
      flash.now[:notice] = 'Please try again!'
      render :new
    end
  end

  def show
    user = User.find(params[:id])
    @upcoming_user_events = user.attended_events.upcoming
    @past_user_events = user.attended_events.past
    @creators_events = user.created_events
  end

  def edit; end

  def update
    @user.update(user_params)

    redirect_to @user, notice: 'User Account Updated'
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Account deleted succesfully'
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def set_params
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_name(*)
    link_to current_user.name, user_path(current_user), class: 'nav-link btn' if current_user
  end

  def user_links(*)
    if current_user
      link_to 'Sign Out', session_path, method: :delete, class: 'nav-link'
    else
      link_to 'Sign Up', new_user_path, class: 'nav-link'
    end
  end

  def user_links2(*)
    link_to 'Sign In', new_session_path, class: 'nav-link' unless current_user
  end

  def create_event
    link_to 'Create New Event', new_event_path, class: 'btn btn-info' if current_user
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_creator?
    current_user == @event.creator
  end

  def register_link(*)
    if @current_attendee
      content_tag(:strong, 'You have registered for this event')
    else
      link_to 'Register for Event', event_join_path(event_id: @event.id, user_id: current_user.id), class: 'btn btn-secondary' # rubocop:disable Layout/LineLength
    end
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def actual_user?
    current_user == @user
  end

  def current_user_links(user)
    link_to 'Edit User Account', edit_user_path(user), class: 'btn btn-light' if actual_user?
  end

  def current_user_links2(user)
    link_to 'Delete Account', user_path(user), method: :delete, class: 'btn btn-light ml-2' if actual_user?
  end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <div class="text-center">
    <div>
      <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, autofocus: true %>
      </p>
      <p >
        <%= f.label :description %><br>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </p>
      <p >
        <%= f.label :location %><br>
        <%= f.text_field :location, size: 30 %>
      </p>
      
      <p >
        <%= f.label :starts_at %><br>
        <%= f.datetime_select :starts_at %>
      </p>
      
    </div>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", events_path %>
    </p>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <h1>Edit Event</h1>
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="container">
  <h1 class="display-4 text-center"><%= pluralize(@events.size, 'Event') %></h1>

  <div class="row">
    <% @events.each do |event| %>
      <div class="col-md-4">
        <div class="card mt-3" style="width: 18rem;">
          <div class="card-body ">
            <h5 class="card-title"><%=link_to event.name, event %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= event.location %></h6>
            <p class="card-text"><%= truncate(event.description, length: 40, separator: ' ') %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container"> 
  <h1 class="text-center"> Create New Event </h1>

  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="container">
  <h1> <%= @event.name %> </h1>
  <h4>Event Creator: <%= link_to @event.creator.name, @event.creator %></h4>
  <table class="table table-bordered">
  <thead>
    <tr>
      <th> Description </th>
      <th> Location </th>
      <th> When </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @event.description %> </td>
      <td><%= @event.location %></td>
       <td><%= @event.starts_at %> </td>
    </tr>
  </tbody>
</table>

<p><strong>Attendees: </strong></p>

<ul>
  <% @event.attendees.each do |attendee| %>
		<li>
			<%= link_to attendee.name, attendee %>
		</li>
  <% end %>
</ul>



<% if !event_creator? %>
    <%= register_link({event_id: @event.id, user_id: current_user.id}) %>
<% end %>

<% if event_creator? %>
  <p><strong> Non_Attendees </strong></p>

  <ul>
    <% @users.each do |user| %>
      <% unless @event.attendees.include?(user) %>
        <li>
          <%= link_to user.name %>:  
          <%= link_to 'Invite this User', event_join_path({event_id: @event.id, user_id: user.id}), class: 'btn btn-light' %>
          <hr>
        </li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to 'Edit Event', edit_event_path(@event) %> |
  <%= link_to 'Delete Event', event_path, method: :delete %>
<% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Upcoming Events', events_path, class: 'btn btn-info' %>
  <%= link_to "Past Events", events_filter_past_path, class: 'btn btn-secondary ml-2' %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= user_name(current_user) %>
      </li>
      <li class="nav-item">
        <%= link_to 'All Users', users_path, class: 'nav-link btn' %>
      </li>
      <li class="nav-item">
        <%= user_links(current_user) %>
      </li>
      <li class="nav-item">
        <%= user_links2(current_user) %>
      </li>
    </ul>

  </div>
   <div class="d-flex justify-content-end">
      <%= create_event %>
  </div>
</nav>
<!--
<% if current_user %>
      
        <%#= link_to current_user.name, user_path(current_user), class: 'nav-link btn'  %>
    <li class="nav-item">
      <%= link_to 'Sign Out', session_path, method: :delete, class: 'nav-link' %> 
    </li>
  <% else %>
    <li class="nav-item">
     
    </li>
   <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %> 
    <li class="nav-item">
      <%= link_to 'Sign In', new_session_path, class: 'nav-link' %>
    </li>
  <% end %>

  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="text-center"><%= flash[:notice] %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="container">
  <div class="form-group" >
    <%= form_for @user do |f| %>
      <p>
        <%= f.label :name%>
      </p>  
      <p>
        <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Enter Name"  %>
      </p>
      <% if @user.new_record? %>
        <%= f.submit 'Create User', class: 'btn btn-primary' %>
      <% else %>
        <%= f.submit 'Update User', class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </form>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit Account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">

  <h1 class="text-center">All Users</h1>
<header>
  <h3 class="navbar-brand">Hello <%= current_user.name %></h3>
</header>

<% @users.each do |user| %>
  <ul class="list-group mt-4">
    <li class="list-group-item">
      <%= link_to user.name, user_path(user) %>
    </li>
  </ul>
<% end %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Create New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.name %></h1>
<div class="container">
<div class="text-center">

  <h4><strong> Events You Created </strong></h4>
<ol class="list-unstyled">
  <% @creators_events.each do |event| %>
      <li>
        <%= link_to event.name, event %>
      </li>
  <% end %>
</ol>
<hr>  
  <h5><strong> Past Events </strong></h5>
  <ol class="list-unstyled">
    <% @past_user_events.each do |event| %>
      <li>
        <%= link_to event.name, event %>
      </li>
    <% end %>
  </ol>
  <hr>
  <h5><strong> Upcoming Events To Attend </strong></h5>

<ol class="list-unstyled">
  <% @upcoming_user_events.each do |event| %>
      <li>
        <%= link_to event.name, event %>
      </li>
  <% end %>
</ol>
</div>
<hr>
  <ul class="nav d-flex justify-content-center mt-5"> 
    <li>
      <%= current_user_links(@user) %>  
    </li>
    <li>
      <%= current_user_links2(@user)  %>
    </li>
  </ul>
</div>